name: TestIsUniformRandomBitGenerator
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Show what to test
      run:  echo "Test; IsUniformRandomBitGenerator"
    - name: Check for g++-10
      run:  |
            if ! command -v g++-10 &> /dev/null; then
              echo "g++-10 is not installed"
              exit 1
            else
              echo "g++-10 is installed"
            fi
    - name: Compile
      run:  g++-10 -std=gnu++20 -O0 -g -rdynamic test/IsUniformRandomBitGenerator/test.cpp
    - uses: actions/checkout@v4
